language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

install:
  - pip install tox-travis

script:
  - tox
  - python setup.py bdist_wheel && ls dist

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false
